version: "3"
services:
  accounts:
    depends_on:
      - mysql_accounts
    image: hunows/account
    build: account
    entrypoint: "npm run start:dev"
    volumes:
      - ./account:/app
    ports:
      - 3000:3000

  mysql_accounts:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=mysqlpass
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=accounts
      - MYSQL_USER=mysqluser
    ports:
      - 3306:3306
